add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_types.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_components.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_stream_channel_reducer.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/util.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/reader.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/sync.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/vocal.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/core.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/marchal.vhd
add_vhdl_file sim_1     WORK ../../../src/test/vhdl/image_stream_models/image_stream_player.vhd
add_vhdl_file sim_1     WORK ../../../src/test/vhdl/image_stream_models/image_stream_master_player.vhd
add_vhdl_file sim_1     WORK ../../../src/test/vhdl/image_stream_models/image_stream_models.vhd
add_vhdl_file sim_1     WORK ../../../src/test/vhdl/image_stream_models/image_stream_slave_player.vhd
add_vhdl_file sim_1     WORK ../../../src/test/vhdl/image_stream_channel_reducer/image_stream_channel_reducer_test_bench.vhd
