add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/components.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/pipeline_register_controller.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_types.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/pipeline_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/unrolled_loop_counter.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_atrb_generator.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_components.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_window_buffer_intake_bank_writer.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_window_buffer_intake_line_selector.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_window_buffer_outlet_bank_reader.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_window_buffer_outlet_line_selector.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_window_buffer_intake.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_window_buffer_outlet.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram_altera_auto_select.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram_model.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram_xilinx_auto_select.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_window_buffer.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/util.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/reader.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/sync.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/vocal.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/core.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/marchal.vhd
add_vhdl_file sim_1     WORK ../../../src/test/vhdl/image_window_models/image_window_player.vhd
add_vhdl_file sim_1     WORK ../../../src/test/vhdl/image_window_models/image_window_master_player.vhd
add_vhdl_file sim_1     WORK ../../../src/test/vhdl/image_window_models/image_window_models.vhd
add_vhdl_file sim_1     WORK ../../../src/test/vhdl/image_window_models/image_window_slave_player.vhd
add_vhdl_file sim_1     WORK ../../../src/test/vhdl/image_window_buffer/image_window_buffer_test_bench.vhd
