add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/components.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/float_intake_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/float_outlet_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_types.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/count_down_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/count_up_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/delay_adjuster.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/delay_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/float_intake_manifold_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/float_outlet_manifold_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/queue_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/reducer.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/syncronizer.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/syncronizer_input_pending_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/pump/pump_components.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/pump/pump_control_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_components.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_data_port.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/chopper.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/pool_outlet_port.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/pump/pump_flow_syncronizer.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/pump/pump_request_controller.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_data_outlet_port.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_master_address_channel_controller.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_master_transfer_queue.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/pool_intake_port.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/queue_receiver.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/pump/pipe_requester_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/pump/pipe_responder_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_master_read_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_master_write_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_slave_read_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_slave_write_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram_xilinx_auto_select.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/pump/pipe_controller.vhd
add_vhdl_file sources_1 WORK ../../../src/test/vhdl/axi4_adapter/axi4_read_adapter.vhd
add_vhdl_file sources_1 WORK ../../../src/test/vhdl/axi4_adapter/axi4_write_adapter.vhd
add_vhdl_file sources_1 WORK ../../../src/test/vhdl/axi4_adapter/axi4_adapter.vhd
