add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/components.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/pipeline_register_controller.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_types.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/pipeline_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/unrolled_loop_counter.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_components.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_stream_atrb_generator.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_stream_buffer_bank_memory_reader.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_stream_buffer_bank_memory_writer.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/convolution/convolution_int_adder.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/convolution/convolution_types.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_stream_buffer_bank_memory.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_stream_buffer_intake_line_selector.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_stream_buffer_outlet_line_selector.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_stream_channel_reducer.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/convolution/convolution_components.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/convolution/convolution_int_accumulator.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/convolution/convolution_int_adder_tree.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/convolution/convolution_int_multiplier.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/image/image_stream_buffer.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/convolution/convolution_int_core.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram_altera_auto_select.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram_model.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram_xilinx_auto_select.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram_xilinx_ultrascale_auto_select.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/util.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/reader.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/sync.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/vocal.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/core.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../../Dummy_Plug/src/main/vhdl/core/marchal.vhd
add_vhdl_file sim_1     WORK ../../../src/test/vhdl/image_stream_models/image_stream_player.vhd
add_vhdl_file sim_1     WORK ../../../src/test/vhdl/image_stream_models/image_stream_master_player.vhd
add_vhdl_file sim_1     WORK ../../../src/test/vhdl/image_stream_models/image_stream_models.vhd
add_vhdl_file sim_1     WORK ../../../src/test/vhdl/image_stream_models/image_stream_slave_player.vhd
add_vhdl_file sim_1     WORK ../../../src/test/vhdl/convolution_int_core/convolution_int_core_test_bench.vhd
