add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_types.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/components.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/queue_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/reducer.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_components.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_data_port.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/chopper.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/float_intake_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/float_outlet_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/pool_outlet_port.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_data_outlet_port.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/count_down_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/count_up_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/delay_adjuster.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/delay_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/float_intake_manifold_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/float_outlet_manifold_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/syncronizer.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/syncronizer_input_pending_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/pump/pump_components.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/pump/pump_control_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_master_address_channel_controller.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_master_transfer_queue.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_register_read_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_register_write_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/pool_intake_port.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/queue_arbiter.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/queue_receiver.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/register_access_decoder.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/register_access_syncronizer.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/pump/pump_controller_intake_side.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/pump/pump_controller_outlet_side.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/pump/pump_flow_syncronizer.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_master_read_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_master_write_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/axi4/axi4_register_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/queue_arbiter_integer_arch.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/queue_arbiter_one_hot_arch.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/register_access_adapter.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram_altera_auto_select.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram_model.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram_xilinx_auto_select.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/components/sdpram_xilinx_ultrascale_auto_select.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/pump/pump_controller.vhd
add_vhdl_file sources_1 PIPEWORK ../../../PipeWork/src/pump/pump_operation_processor.vhd
add_vhdl_file sources_1 WORK ../../../src/test/vhdl/pump_axi4/pump_axi4_to_axi4_core.vhd
add_vhdl_file sources_1 WORK ../../../src/test/vhdl/pump_axi4/pump_axi4_to_axi4.vhd
